using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReDpett.ViewModel
{
    public class RegisterViewModel
    {

        //[Required(ErrorMessage = "Id is required")]
        public int RegisterID { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Last Name is required.")]
        public string LastName { get; set; }
        [EmailAddress]
        [Required(ErrorMessage = "Email is required.")]
        public string? Email { get; set; }

        [RegularExpression(@"^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$",
            ErrorMessage = "Password should have minimum eight characters, at least 1 upper case, 1 lower case, 1 digit, 1 special character.")]

        public string Password { get; set; }


        [Required(ErrorMessage = "Country is required.")]
        public int CountryId { get; set; }
        [Required(ErrorMessage = "FETP Program is required.")]
        public int FETPProgramId { get; set; }
        [Required(ErrorMessage = "Role is required.")]
        public int RoleId { get; set; }
        
        public int NonResidentId { get; set; }
        [Required]
        [Display(Name = "Confirm Password.")]
        [Compare("Password", ErrorMessage = "The password and confirm password fields do not match.")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Passcode is required.")]
        public string? Passcode { get; set; }


        public string? ResidentPasscode { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string FETP { get; set; }
        public string FETPLevel { get; set; }
        public bool? isAutoGenerated { get; set; }


    }
}
