using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ReDpett.Modal
{
    public class Register
    {
        //[Required(ErrorMessage = "Id is required")]
        public int RegisterID { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Last Name is required")]
        public string LastName { get; set; }
        [EmailAddress]
        [Required(ErrorMessage = "Email is required")]
        public string? Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Country is required")]
        public int CountryId { get; set; }
        [Required(ErrorMessage = "FETP Program is required")]
        public int FETPProgramId { get; set; }        
        [Required(ErrorMessage = "Role is required")]
        public int RoleId { get; set; }
        public int NonResidentId { get; set; }


        [Required(ErrorMessage = "Passcode is required")]
        public string? Passcode { get; set; }
        public string? Region { get; set; }
        public string? Country { get; set; }
        public string? FETP { get; set; }
        public string? FETPLevel { get; set; }
        public bool? isAutoGenerated { get; set; }
    }//[Route("/Register/User")]
     //[JsonConverter(typeof(JsonStringEnumConverter))]
     //public enum Country
     //{
     //    Ghana = 1,
     //    Nepal,
     //    USA,
     //    UAE,
     //    India,
     //    Srilanka,
     //    Bhutan
     //}
     //[JsonConverter(typeof(JsonStringEnumConverter))]
     //public enum Non_FETPProgram
     //{
     //    Frontline = 1,
     //    Intermediate,
     //    Advanced

    //}


}
